export type Category = "ai-native" | "ai-transformed" | "traditional";

export interface GuideEntry {
  id: number;
  slug: string;
  name: string;
  icon: string;
  category: Category;
  categoryLabel: string;
  categoryColor: string;
  tagline: string;
  whatIsIt: string;
  howItWorks: string[];
  redFlags: string[];
  whatToDo: string[];
  stat: string;
  teenStory: string;
  pokedexSlug?: string;
}

export const CATEGORY_META: Record<
  Category,
  { label: string; color: string; description: string }
> = {
  "ai-native": {
    label: "AI-Native",
    color: "#ff1744",
    description: "",
  },
  "ai-transformed": {
    label: "AI-Transformed",
    color: "#ff6d00",
    description: "",
  },
  traditional: {
    label: "Traditional",
    color: "#00d4ff",
    description: "",
  },
};

export const GUIDE_ENTRIES: GuideEntry[] = [
  // ── AI-NATIVE ─────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: "voice-cloning",
    name: "",
    icon: "🎙️",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 2,
    slug: "deepfake-video",
    name: "",
    icon: "🎭",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 3,
    slug: "romance-bot",
    name: "",
    icon: "💔",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 4,
    slug: "ai-job-scam",
    name: "",
    icon: "💼",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 5,
    slug: "deepfake-id",
    name: "",
    icon: "🆔",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 6,
    slug: "ai-fake-celebrity",
    name: "",
    icon: "⭐",
    category: "ai-native",
    categoryLabel: "AI-Native",
    categoryColor: "#ff1744",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },

  // ── AI-TRANSFORMED ────────────────────────────────────────────────────────
  {
    id: 7,
    slug: "ai-phishing",
    name: "",
    icon: "📧",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    categoryColor: "#ff6d00",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 8,
    slug: "ai-robocall",
    name: "",
    icon: "📞",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    categoryColor: "#ff6d00",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 9,
    slug: "ai-sextortion",
    name: "",
    icon: "🔒",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    categoryColor: "#ff6d00",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 10,
    slug: "ai-tech-support",
    name: "",
    icon: "🖥️",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    categoryColor: "#ff6d00",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 11,
    slug: "ai-crypto-scam",
    name: "",
    icon: "💰",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    categoryColor: "#ff6d00",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },

  // ── TRADITIONAL ───────────────────────────────────────────────────────────
  {
    id: 12,
    slug: "gift-card-scam",
    name: "",
    icon: "🎁",
    category: "traditional",
    categoryLabel: "Traditional",
    categoryColor: "#00d4ff",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 13,
    slug: "fake-job-listing",
    name: "",
    icon: "📋",
    category: "traditional",
    categoryLabel: "Traditional",
    categoryColor: "#00d4ff",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 14,
    slug: "fake-giveaway",
    name: "",
    icon: "🎉",
    category: "traditional",
    categoryLabel: "Traditional",
    categoryColor: "#00d4ff",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 15,
    slug: "scholarship-scam",
    name: "",
    icon: "🎓",
    category: "traditional",
    categoryLabel: "Traditional",
    categoryColor: "#00d4ff",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
  {
    id: 16,
    slug: "p2p-payment-fraud",
    name: "",
    icon: "💸",
    category: "traditional",
    categoryLabel: "Traditional",
    categoryColor: "#00d4ff",
    tagline: "",
    whatIsIt: "",
    howItWorks: [],
    redFlags: [],
    whatToDo: [],
    stat: "",
    teenStory: "",
  },
];
