export type ThreatLevel = "critical" | "high" | "medium";

export interface ScamItem {
  id: string;
  name: string;
  summary: string;
  rank: number;
  riskLevel: ThreatLevel;
  category: "ai-native" | "ai-transformed" | "traditional";
  categoryLabel: string;
  reportsThisWeek: number;
  reportsDelta: number;
  isSpiking: boolean;
  isTop: boolean;
  reportedAt: string;
  tips: string[];
  image: string;
}

export const SCAMS: ScamItem[] = [
  {
    id: "ai-voice-clone-emergency",
    name: "AI Voice Clone Emergency Call",
    summary: "Scammers clone a family member's voice from 3 seconds of social media audio, then call parents claiming they've been in an accident or arrested. A second AI voice poses as a lawyer demanding immediate wire transfer or gift card 'bail'. Tens of thousands of reports filed with the FTC — one family lost $15,000 in a single afternoon.",
    rank: 1,
    riskLevel: "critical",
    category: "ai-native",
    categoryLabel: "AI-Native",
    reportsThisWeek: 3840,
    reportsDelta: 62,
    isSpiking: true,
    isTop: true,
    reportedAt: "May 5",
    tips: [
      "Hang up immediately and call the person back on a number you already have saved — don't use any number the caller gives you.",
      "Set up a family safe word only you and your immediate family know. If they can't say it, it's a scam.",
      "Never wire money, send gift cards, or do a cryptocurrency transfer based on any phone call, no matter how convincing the voice sounds.",
      "3 seconds of public audio is all it takes to clone a voice. Any urgent, emotional call requesting money should be verified in person or by callback.",
    ],
    image: "https://images.unsplash.com/photo-UwnH5jSrdr4?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "pig-butchering-romance-bot",
    name: "Pig Butchering Romance Bot",
    summary: "AI chatbots simulate a romantic partner over weeks on dating apps and Instagram DMs, then pivot to a fake crypto investment platform. The bot always has an excuse to avoid a live unscripted video call. Americans lost $11.37 billion to this scam type in 2025 — the fastest-growing fraud category due to AI automation.",
    rank: 2,
    riskLevel: "critical",
    category: "ai-native",
    categoryLabel: "AI-Native",
    reportsThisWeek: 3210,
    reportsDelta: 48,
    isSpiking: true,
    isTop: false,
    reportedAt: "May 5",
    tips: [
      "Ask for a spontaneous, unscripted live video call — AI bots can't do this and will always make an excuse.",
      "Reverse image search every profile photo. AI-generated faces leave subtle artifacts around ears, hair edges, and backgrounds.",
      "Never invest in any platform introduced by someone you met online, no matter how long you've been talking.",
      "The 'pig butchering' name comes from fattening the victim's trust before slaughter. Weeks of charm followed by a crypto pitch is the defining pattern.",
    ],
    image: "https://images.unsplash.com/photo-cQagZjqw88k?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "ai-sextortion-nudify",
    name: "AI Sextortion — Nudify Deepfake",
    summary: "Attackers run innocent photos from Instagram or Snapchat through AI 'nudifier' apps, then threaten to share the fake explicit images unless the victim pays or sends real images. Risk of sextortion in the U.S. rose 137% in 2025. Boys aged 14–17 are the most targeted demographic. Never pay — it always escalates.",
    rank: 3,
    riskLevel: "critical",
    category: "ai-native",
    categoryLabel: "AI-Native",
    reportsThisWeek: 2750,
    reportsDelta: 137,
    isSpiking: true,
    isTop: false,
    reportedAt: "May 4",
    tips: [
      "Never pay. Every payment proves you're scared and makes the demands escalate — they will always ask for more.",
      "Screenshot everything and report immediately to the NCMEC CyberTipline at CyberTipline.org or 1-800-843-5678.",
      "Block the attacker on every platform and do not respond further. Engagement is what they want.",
      "Tell a trusted adult. This is not your fault — the fake images are AI-generated and courts recognize that.",
    ],
    image: "https://images.unsplash.com/photo-2YjIz_cc1QU?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "deepfake-video-call-fraud",
    name: "Deepfake Video Call Fraud",
    summary: "Real-time AI deepfakes of bosses, CEOs, or authority figures on Zoom or FaceTime are used to instruct victims to wire money or hand over credentials. UK engineering firm Arup lost $25 million in a single deepfake CFO call in 2024. Documented deepfake fraud losses exceeded $200 million in Q1 2025 alone.",
    rank: 4,
    riskLevel: "critical",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    reportsThisWeek: 2180,
    reportsDelta: 44,
    isSpiking: true,
    isTop: false,
    reportedAt: "May 3",
    tips: [
      "Call back on the number you already have stored for that person — don't use any contact info from the suspicious call.",
      "Ask a rapid personal question only the real person would know. Deepfakes can't improvise specific memories.",
      "Ask them to wave quickly or touch their face — real-time deepfakes still struggle with fast, unexpected movements.",
      "No legitimate authority will pressure you to wire funds or share credentials during a single video call. That urgency is the attack.",
    ],
    image: "https://images.unsplash.com/photo-72LU8QlGs5E?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "ai-hyper-personalized-phishing",
    name: "AI Hyper-Personalized Phishing",
    summary: "AI tools scrape your name, school, workplace, and recent posts to craft perfectly personalized phishing emails with zero grammar errors and no generic greetings. Phishing attacks increased 1,265% since generative AI went mainstream — 82.6% of detected phishing emails are now AI-written. The old tells are completely gone.",
    rank: 5,
    riskLevel: "high",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    reportsThisWeek: 1920,
    reportsDelta: 38,
    isSpiking: false,
    isTop: false,
    reportedAt: "May 2",
    tips: [
      "Hover over every link before clicking — the visible text and the actual URL are often different.",
      "Go directly to websites by typing the address yourself instead of clicking links in emails or DMs.",
      "Bad grammar and generic greetings are no longer reliable red flags. Treat any urgent request — even a perfect one — with suspicion.",
      "Enable two-factor authentication everywhere so that even if credentials are stolen, the attacker can't get in.",
    ],
    image: "https://images.unsplash.com/photo-8VdHghrvC0k?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "fake-ai-recruiter-job-scam",
    name: "Fake AI Recruiter / Job Scam",
    summary: "AI-generated recruiter profiles and job listings on LinkedIn and Indeed lure victims into fake onboarding flows that collect SSN, bank account numbers, and ID photos for identity theft — or demand upfront 'training fees'. FTC received 105,000 job scam reports in 2024, with losses jumping from $90M to $513M year-over-year.",
    rank: 6,
    riskLevel: "high",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    reportsThisWeek: 1540,
    reportsDelta: 29,
    isSpiking: false,
    isTop: false,
    reportedAt: "Apr 30",
    tips: [
      "Call the company's official listed number to verify the offer before submitting any documents.",
      "Real employers never ask for your SSN, bank routing number, or photo ID before your first day.",
      "Any job that requires you to pay upfront for training, equipment, or a background check is a scam.",
      "Check the recruiter's LinkedIn — AI-generated profiles often have suspiciously perfect photos and very short employment histories.",
    ],
    image: "https://images.unsplash.com/photo-l4Zu0xVCFfI?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "celebrity-deepfake-crypto-ad",
    name: "Celebrity Deepfake Crypto Ad",
    summary: "AI-generated videos of Elon Musk, Taylor Swift, and MrBeast run as paid social media ads promoting fake crypto giveaways and investment platforms. The Nomani investment scam using this tactic surged 62% in 2025. Humans correctly identify high-quality deepfake video only 24.5% of the time — your eyes can no longer be trusted.",
    rank: 7,
    riskLevel: "high",
    category: "ai-native",
    categoryLabel: "AI-Native",
    reportsThisWeek: 1190,
    reportsDelta: 62,
    isSpiking: true,
    isTop: false,
    reportedAt: "Apr 28",
    tips: [
      "No celebrity is ever giving away free money online. If you see it, it is fake — 100% of the time.",
      "Check the person's verified official account to see if they're actually promoting it.",
      "Legitimate crypto investments don't require you to send money first to 'unlock' your returns.",
      "You correctly identify high-quality deepfake video only 24.5% of the time — your eyes alone are not enough.",
    ],
    image: "https://images.unsplash.com/photo-ZAIbez5LTrg?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "ai-gov-impersonation-robocall",
    name: "AI Government Impersonation Robocall",
    summary: "AI voices impersonate IRS agents, Social Security officials, or FBI investigators, claiming your SSN is suspended or an arrest warrant is active. Government impersonation complaints nearly doubled from 17,300 to 32,500 in 2025, with losses hitting $797M. The IRS never calls to demand immediate payment or threaten arrest.",
    rank: 8,
    riskLevel: "high",
    category: "ai-transformed",
    categoryLabel: "AI-Transformed",
    reportsThisWeek: 980,
    reportsDelta: 34,
    isSpiking: false,
    isTop: false,
    reportedAt: "Apr 25",
    tips: [
      "Hang up and call the agency directly using the number on their official .gov website — never the number the caller gives you.",
      "The IRS contacts taxpayers by mail first. SSA and FBI do not call to threaten immediate arrest.",
      "Gift cards, wire transfers, and cryptocurrency are never valid forms of government payment. Ever.",
      "Save the number at irs.gov (1-800-829-1040) so you can call back to verify any claim.",
    ],
    image: "https://images.unsplash.com/photo-n8kmAFCMwhg?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "ai-tech-support-popup",
    name: "AI Tech Support Pop-Up Scam",
    summary: "Fake browser alerts or AI robocalls impersonating Microsoft or Apple claim your device is infected. A convincing AI voice guides you to install remote access software, then steals passwords and bank details directly. Tech support scams caused $2.1 billion in losses in 2025 — Microsoft now blocks over 4,400 suspicious remote access attempts per day.",
    rank: 9,
    riskLevel: "medium",
    category: "traditional",
    categoryLabel: "Traditional",
    reportsThisWeek: 720,
    reportsDelta: 18,
    isSpiking: false,
    isTop: false,
    reportedAt: "Apr 22",
    tips: [
      "Never call a phone number that appears in a browser pop-up or full-screen alert — real OS alerts don't work that way.",
      "Never install AnyDesk, TeamViewer, or any remote access software because a stranger told you to.",
      "Microsoft and Apple do not proactively call you about viruses on your device.",
      "If your browser is locked up, force-quit the app (Cmd+Q on Mac, Alt+F4 on Windows) — you are not infected.",
    ],
    image: "https://images.unsplash.com/photo-4OkY858eLVI?w=600&h=400&fit=crop&auto=format",
  },
  {
    id: "zelle-bank-impersonation-fraud",
    name: "Zelle Bank Impersonation Fraud",
    summary: "A caller impersonates your bank's fraud department, warns of suspicious activity on your account, and instructs you to 'protect' your money by Zelling it to a 'safe account' they control. Banks processed $870 million in these authorized push-payment losses in 2024. Because you initiate the transfer yourself, banks routinely deny refund claims — leaving victims with nothing.",
    rank: 10,
    riskLevel: "high",
    category: "traditional",
    categoryLabel: "Traditional",
    reportsThisWeek: 1380,
    reportsDelta: 41,
    isSpiking: true,
    isTop: false,
    reportedAt: "May 7",
    tips: [
      "Hang up and call the number printed on the back of your debit card — never use a number the incoming caller provides.",
      "Your bank will never ask you to move money to a 'safe account' via Zelle, Venmo, or wire. That phrase is always the scam.",
      "Authorized push-payment fraud is the #1 reason banks deny refunds — once you send via Zelle, recovery is extremely rare.",
      "If you feel pressured to act within minutes, that urgency is the attack. Go to a physical branch to verify before touching anything.",
    ],
    image: "https://images.unsplash.com/photo-HI04JoIfjjc?w=600&h=400&fit=crop&auto=format",
  },
];
